version: '3.1'

services:
  db:
    image: postgres:latest
    build:
        context: ./Datenbank
        dockerfile: Dockerfile
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: SicheresPasswort!
      POSTGRES_DB: pong_daten
    ports:
      - "5432:5432"
  backend:
    build:
        context: ./api-backend
        dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
  game:
    build:
        context: ./game
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
volumes:
  postgressql:
